spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2205
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: bokgosha@yandex.ru
    password: qtxselgtcdgeljsm

application:
  persistent-dir: D:\Projects\IdeaProjects\pr_19\backUps